blank_issues_enabled: false
contact_links:
  - name: Make a discussion
    url: https://github.com/my-little-lab/angular-boilerplate/discussions/new/choose
    about: Fully discuss with the team members to identify the issue before submitting a report.
