name: Feature request (beta)
description: Suggest an idea for this project
title: '[Feature] '
labels: [enhancement]
assignees: 
  - jessieher
  - jessaher
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to fill out a feature request!
        **Before filling out this report**, please check [existing feature requests](/my-little-lab/demo-repository/issues?q=is%3Aissue++label%3Aenhancement+) and see if your feature has already been proposed.

        Please describe your feature request with as many details as possible.
        > Tips: You can attach images or files by clicking the textarea to highlight it and then dragging files in.

  - type: textarea
    attributes:
      label: Related Problem
      description: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]

  - type: textarea
    attributes:
      label: Solution
      description: |
        Describe the solution you'd like.
        A clear and concise description of what you want to happen. 

  - type: textarea
    attributes:
      label: Alternative
      description: |
        Describe alternatives you've considered.
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
 
