name: Auto Assign
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR reviewers and assignees
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto-assign.yml'
